-- GENERATED by scripts/build-sql.js - edit scripts/catalog.js instead.
-- Upgrade an existing cartiva database in place (safe to run once).
USE cartiva;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  address VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(100),
  pincode VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(120) NOT NULL UNIQUE,
  image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  category_id INT,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  discount DECIMAL(5,2) NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  image VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_products_category (category_id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cart_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cart_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  UNIQUE KEY uq_cart_product (cart_id, product_id),
  FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  address VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(100),
  pincode VARCHAR(10),
  payment_method VARCHAR(50),
  status VARCHAR(30) DEFAULT 'Order Placed',
  cancelled_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

ALTER TABLE users ADD COLUMN address VARCHAR(255), ADD COLUMN city VARCHAR(100),
  ADD COLUMN state VARCHAR(100), ADD COLUMN pincode VARCHAR(10);
ALTER TABLE orders ADD COLUMN cancelled_at TIMESTAMP NULL;
ALTER TABLE orders MODIFY status VARCHAR(30) DEFAULT 'Order Placed';
ALTER TABLE products MODIFY discount DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE cart_items ADD UNIQUE KEY uq_cart_product (cart_id, product_id);

INSERT INTO categories (id, name, slug, image) VALUES
(1, 'Electronics', 'electronics', 'image/categories/electronics.jpg'),
(2, 'Fashion', 'fashion', 'image/categories/fashion.jpg'),
(3, 'Home & Kitchen', 'home-kitchen', 'image/categories/home-kitchen.jpg'),
(4, 'Beauty & Care', 'beauty-care', 'image/categories/beauty-care.jpg'),
(5, 'Sports & Fitness', 'sports-fitness', 'image/categories/sports-fitness.jpg'),
(6, 'Books & Stationery', 'books-stationery', 'image/categories/books-stationery.jpg')
ON DUPLICATE KEY UPDATE name = VALUES(name), slug = VALUES(slug), image = VALUES(image);

-- Remove the 3 original placeholder products only if nothing references them
DELETE FROM products WHERE id IN (1, 2, 3) AND image = 'image/product-placeholder.jpg'
  AND id NOT IN (SELECT product_id FROM order_items)
  AND id NOT IN (SELECT product_id FROM cart_items);
INSERT INTO products (name, category_id, description, price, discount, stock, image) VALUES
('Wireless Noise-Cancelling Headphones', 1, 'Over-ear Bluetooth headphones with active noise cancelling and 30-hour battery life.', 2999, 10, 50, 'image/products/wireless-noise-cancelling-headphones.jpg'),
('Smart Fitness Watch', 1, 'Heart-rate, sleep and step tracking with a bright AMOLED display and 7-day battery.', 4999, 15, 30, 'image/products/smart-fitness-watch.jpg'),
('Portable Bluetooth Speaker', 1, 'Water-resistant 360-degree speaker with deep bass and 12 hours of playtime.', 1999, 20, 80, 'image/products/portable-bluetooth-speaker.jpg'),
('Ultra-Slim Laptop 14 inch', 1, 'Lightweight 14-inch laptop, 16 GB RAM, 512 GB SSD, all-day battery.', 54999, 8, 15, 'image/products/ultra-slim-laptop-14-inch.jpg'),
('Lightweight Running Shoes', 2, 'Breathable mesh running shoes with cushioned midsole and grippy outsole.', 1999, 0, 100, 'image/products/lightweight-running-shoes.jpg'),
('Classic Cotton T-Shirt', 2, 'Soft 100% combed-cotton crew-neck tee in a regular fit.', 599, 25, 200, 'image/products/classic-cotton-t-shirt.jpg'),
('Windproof Casual Jacket', 2, 'Water-repellent, windproof jacket with zip pockets, ideal for all seasons.', 3499, 30, 40, 'image/products/windproof-casual-jacket.jpg'),
('Polarised Sunglasses', 2, 'UV400 polarised lenses in a lightweight, durable frame.', 1299, 12, 60, 'image/products/polarised-sunglasses.jpg'),
('Modern Table Lamp', 3, 'Warm-light bedside lamp with a fabric shade and sturdy metal base.', 1499, 15, 45, 'image/products/modern-table-lamp.jpg'),
('Electric Kettle 1.8L', 3, 'Fast-boil stainless-steel kettle with auto shut-off and boil-dry protection.', 1199, 10, 70, 'image/products/electric-kettle-1-8l.jpg'),
('Non-Stick Frying Pan', 3, 'Induction-friendly 28 cm non-stick pan with a heat-resistant handle.', 899, 20, 90, 'image/products/non-stick-frying-pan.jpg'),
('Memory Foam Pillow', 3, 'Ergonomic memory-foam pillow that supports neck and shoulders.', 999, 18, 55, 'image/products/memory-foam-pillow.jpg'),
('Daily Moisturising Cream', 4, 'Lightweight 24-hour hydrating cream for all skin types.', 449, 10, 120, 'image/products/daily-moisturising-cream.jpg'),
('Eau de Parfum 50ml', 4, 'Long-lasting floral-woody fragrance in a 50 ml glass bottle.', 2499, 22, 35, 'image/products/eau-de-parfum-50ml.jpg'),
('Matte Lipstick', 4, 'Highly pigmented, non-drying matte lipstick that lasts through the day.', 599, 0, 150, 'image/products/matte-lipstick.jpg'),
('Vitamin C Face Serum', 4, 'Brightening 10% Vitamin C serum with hyaluronic acid.', 799, 15, 85, 'image/products/vitamin-c-face-serum.jpg'),
('Adjustable Dumbbell Set', 5, 'Space-saving adjustable dumbbells, 2-20 kg per hand, with a storage tray.', 3999, 12, 25, 'image/products/adjustable-dumbbell-set.jpg'),
('Anti-Slip Yoga Mat', 5, '6 mm thick, non-slip, eco-friendly TPE yoga mat with a carry strap.', 999, 20, 75, 'image/products/anti-slip-yoga-mat.jpg'),
('Insulated Water Bottle 1L', 5, 'Double-wall steel bottle that keeps drinks cold for 24 h or hot for 12 h.', 699, 5, 110, 'image/products/insulated-water-bottle-1l.jpg'),
('Match Football Size 5', 5, 'Machine-stitched size-5 football with durable synthetic cover.', 1199, 10, 65, 'image/products/match-football-size-5.jpg'),
('The Art of Focus (Paperback)', 6, 'A practical guide to deep work, habits and productivity.', 399, 0, 140, 'image/products/the-art-of-focus-paperback.jpg'),
('Hardcover Ruled Notebook', 6, 'A5 hardcover notebook, 200 pages of 100 gsm acid-free paper.', 249, 10, 300, 'image/products/hardcover-ruled-notebook.jpg'),
('Premium Gel Pen Set of 5', 6, 'Smooth-writing 0.5 mm gel pens in five colours.', 199, 0, 400, 'image/products/premium-gel-pen-set-of-5.jpg'),
('Everyday Laptop Backpack', 6, 'Water-resistant 25 L backpack with padded laptop sleeve and USB port.', 1799, 25, 50, 'image/products/everyday-laptop-backpack.jpg');

ALTER TABLE products ADD INDEX idx_products_category (category_id);
ALTER TABLE products ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
