/* Builds database/cartiva.sql (fresh install) and database/migrate.sql
   (upgrade an existing cartiva DB). Run: node scripts/build-sql.js */
const fs = require("fs");
const path = require("path");
const bcrypt = require("../backend/node_modules/bcryptjs");
const { CATEGORIES, PRODUCTS } = require("./catalog.js");

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const adminHash = bcrypt.hashSync("admin123", 10);

const schema = `
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  address VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(100),
  pincode VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(120) NOT NULL UNIQUE,
  image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  category_id INT,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  discount DECIMAL(5,2) NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  image VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_products_category (category_id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cart_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cart_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  UNIQUE KEY uq_cart_product (cart_id, product_id),
  FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  address VARCHAR(255),
  city VARCHAR(100),
  state VARCHAR(100),
  pincode VARCHAR(10),
  payment_method VARCHAR(50),
  status VARCHAR(30) DEFAULT 'Order Placed',
  cancelled_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id)
);
`;

const seedCategories = "INSERT INTO categories (id, name, slug, image) VALUES\n" +
    CATEGORIES.map((c) => `(${c.id}, ${q(c.name)}, ${q(c.slug)}, ${q("image/categories/" + c.slug + ".jpg")})`).join(",\n") +
    "\nON DUPLICATE KEY UPDATE name = VALUES(name), slug = VALUES(slug), image = VALUES(image);\n";

const productRow = (p) =>
    `(${q(p.name)}, ${p.category_id}, ${q(p.description)}, ${p.price}, ${p.discount}, ${p.stock}, ${q("image/products/" + p.slug + ".jpg")})`;
const seedProducts = "INSERT INTO products (name, category_id, description, price, discount, stock, image) VALUES\n" +
    PRODUCTS.map(productRow).join(",\n") + ";\n";

const adminSeed = `INSERT INTO users (name, email, phone, password, role)
SELECT 'Admin', 'admin@cartiva.com', '9999999999', ${q(adminHash)}, 'admin' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@cartiva.com');
`;

const header = "-- GENERATED by scripts/build-sql.js - edit scripts/catalog.js instead.\n";

fs.writeFileSync(path.join(__dirname, "..", "database", "cartiva.sql"),
    `${header}-- Fresh install. Admin login: admin@cartiva.com / admin123 (change it!)
CREATE DATABASE IF NOT EXISTS cartiva;
USE cartiva;
${schema}
${seedCategories}
${seedProducts}
${adminSeed}`);

// Upgrade path for a database created from the earlier schema. Keeps users,
// orders and carts; replaces only the three original sample products.
fs.writeFileSync(path.join(__dirname, "..", "database", "migrate.sql"),
    `${header}-- Upgrade an existing cartiva database in place (safe to run once).
USE cartiva;
${schema}
ALTER TABLE users ADD COLUMN address VARCHAR(255), ADD COLUMN city VARCHAR(100),
  ADD COLUMN state VARCHAR(100), ADD COLUMN pincode VARCHAR(10);
ALTER TABLE orders ADD COLUMN cancelled_at TIMESTAMP NULL;
ALTER TABLE orders MODIFY status VARCHAR(30) DEFAULT 'Order Placed';
ALTER TABLE products MODIFY discount DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE cart_items ADD UNIQUE KEY uq_cart_product (cart_id, product_id);

${seedCategories}
-- Remove the 3 original placeholder products only if nothing references them
DELETE FROM products WHERE id IN (1, 2, 3) AND image = 'image/product-placeholder.jpg'
  AND id NOT IN (SELECT product_id FROM order_items)
  AND id NOT IN (SELECT product_id FROM cart_items);
${seedProducts}
ALTER TABLE products ADD INDEX idx_products_category (category_id);
ALTER TABLE products ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
`);
console.log("wrote database/cartiva.sql and database/migrate.sql");
